
server:
  port: 8094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: himanshubector
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


